public enum EUpgradable
{
	None = 0,
	CHARACTER_SPEED = 1,
	CHARACTER_CAPACITY = 2,
	CHARACTER_STORE_SPEED = 3,
	PAPER_DELIVERER_HELPER_SPEED = 4,
	PAPER_DELIVERER_HELPER_CAPACITY = 5,
	PAPER_DELIVERER_HELPER_STORE_SPEED = 6,
	CLASSROOM_1_SPEED = 7,
	CLASSROOM_2_SPEED = 8,
	PAPER_DELIVERER_HELPER_HIRE = 9,
	AUTOMAT_1_CAPACITY = 10,
	TUTORIAL = 11,
}