public enum EUpgradable
{
	None = 0,
	CHARACTER_SPEED = 1,
	CHARACTER_CAPACITY = 2,
	CHARACTER_STORE_SPEED = 3,
	CLASSROOM_SPEED = 4,
	HELPER_SPEED = 5,
	HELPER_CAPACITY = 6,
	HELPER_STORE_SPEED = 7,
	CLASSROOM_1_SPEED = 8,
	CLASSROOM_2_SPEED = 9,
}