public enum EUpgradable
{
	None = 0,
	CHARACTER_SPEED = 1,
	CHARACTER_CAPACITY = 2,
	CHARACTER_STORE_SPEED = 3,
	HELPER_1_SPEED = 4,
	HELPER_1_CAPACITY = 5,
	HELPER_1_STORE_SPEED = 6,
	CLASSROOM_1_SPEED = 7,
	CLASSROOM_2_SPEED = 8,
}